name: core-build-modules
on:
  workflow_call:
    inputs:
      module_repo:
        required: true
        type: string
      module_branch:
        required: false
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler.CC }}
    if: !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'azerothcore/azerothcore-wotlk'
          ref: 'master'
          submodules: 'recursive'
      - uses: actions/checkout@v4
        with:
          repository: 'azerothcore/reusable-workflows'
          path: 'reusable-workflows'
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: 'modules/${{ inputs.module_repo }}'
          ref: ${{ inputs.module_branch }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: var/ccache
          key: ccache:${{ matrix.compiler.CC }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.compiler.CC }}:${{ github.ref }}
            ccache:${{ matrix.compiler.CC }}
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
      - name: cpp check
        run: |
          sudo apt update -y
          sudo apt install -y cppcheck
          cppcheck --force --inline-suppr --suppressions-list=reusable-workflows/cppchecksuppressions.txt --output-file=report.txt modules/
          if [ -s report.txt ]; then
            cat report.txt
            exit 1
          fi
